// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPSDy1mGNSDDP5d_jMHOZjZyz3bBKC4Yg',
    appId: '1:1010967953802:web:23f9fd2d86b137cbe6c873',
    messagingSenderId: '1010967953802',
    projectId: 'app-makefood',
    authDomain: 'app-makefood.firebaseapp.com',
    storageBucket: 'app-makefood.appspot.com',
    measurementId: 'G-LQX9PMGWR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rzWEEUqfE3179I7X9k9L8E-QyzjBBbI',
    appId: '1:1010967953802:android:2524b80c9912038ae6c873',
    messagingSenderId: '1010967953802',
    projectId: 'app-makefood',
    storageBucket: 'app-makefood.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPSDy1mGNSDDP5d_jMHOZjZyz3bBKC4Yg',
    appId: '1:1010967953802:web:cca1e5a77eaada96e6c873',
    messagingSenderId: '1010967953802',
    projectId: 'app-makefood',
    authDomain: 'app-makefood.firebaseapp.com',
    storageBucket: 'app-makefood.appspot.com',
    measurementId: 'G-D5WP9GM185',
  );
}
